### ISSUE TITLE
Reuse b as variable name in lecture 2（This will cause a problem, when the article finally uses ok.score() to judge all the problems, b = np.array([1, 2]).  The actually correct code of question 2.10 which was judged to be correct before will still be judged wrong.）

### ISSUE THREAD

**Issue by acse-6f9303e2** [ese-msc/introduction-to-python#43]
In lecture 2, question 2.10, b is wanted as the name of the vector:

REFERENCE: exercise-2_10
SATISFIED: False
MESSAGES:
  - SUCCESS: Your matrix A is correct. Nice!
  **- SUCCESS: Your vector b is correct. Nice!** 
  - ERROR: You are not populating resulting vector correctly.
  - SUCCESS: Great! You created a zero-vector before the loop.
  - SUCCESS: Wow! The result of your multiplication is correct.

However, This guide reuses b as the variable name in **In [76]:**

A = np.array([[1, 1], [2, 1]])
**b = np.array([1, 2])** 
Ab = A @ b

print(f"{A = }")
print(f"{b = }")
print(f"{Ab = }")

This will cause a problem, **when the article finally uses ok.score() to judge all the problems, b = np.array([1, 2]). 
The actually correct code of question 2.10 which was judged to be correct before will still be judged wrong.**

question 2.10 > Suite 1 > Case 3

import numpy as np
>>> np.allclose(b, [-2, 1, 7])
Traceback (most recent call last):
  File "<__array_function__ internals>", line 180, in allclose
  File "/root/anaconda3/envs/introduction-to-python/lib/python3.9/site-packages/numpy/core/numeric.py", line 2265, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 180, in isclose
  File "/root/anaconda3/envs/introduction-to-python/lib/python3.9/site-packages/numpy/core/numeric.py", line 2375, in isclose
    return within_tol(x, y, atol, rtol)
  File "/root/anaconda3/envs/introduction-to-python/lib/python3.9/site-packages/numpy/core/numeric.py", line 2356, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (2,) (3,) 

**Solution: delete the following b variable definition.**

A = np.array([[1, 1], [2, 1]])
#b = np.array([1, 2])
#Ab = A @ b

print(f"{A = }")
#print(f"{b = }")
#print(f"{Ab = }")

But I think this may confuse some beginners.

**Comment by acse-6f9303e2** [comment]
I just saw that someone has already responded to this question below
