### ISSUE TITLE
Cannot open the JupyterLab link in the intro

### ISSUE THREAD

**Issue by edsml-4c29515f** [ese-msc/introduction-to-python#6]
**I couldn't open the link of Jupyter lab and this is the error:**

Traceback (most recent call last):
File "/opt/jupyter/lib/python3.8/site-packages/nbgitpuller/pull.py", line 90, in branch_exists
    heads = subprocess.run(
File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-remote', '--heads', 'https://github.com/ese-msc/python_exercises']' returned non-zero exit status 128.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/jupyter/lib/python3.8/site-packages/nbgitpuller/handlers.py", line 76, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
File "/opt/jupyter/lib/python3.8/site-packages/nbgitpuller/pull.py", line 77, in __init__
    elif not self.branch_exists(self.branch_name):
File "/opt/jupyter/lib/python3.8/site-packages/nbgitpuller/pull.py", line 112, in branch_exists
    raise ValueError(m)
ValueError: Problem accessing list of branches and/or tags: https://github.com/ese-msc/python_exercises

I think something wrong with the link. Could you please help me?

**Comment by marijanbeg** [comment]
Hi @edsml-4c29515f, thank you for letting us know. You are absolutely right! The link in `README.md` was wrong. This is now fixed :)

Thank you very much for your feedback, and please do not hesitate to raise further issues.
